name: CaptchaVerification
description: Now You can Verify Bot or Human to Join this server
author: MulqiGaming64
version: 1.0.0
api: 4.0.0
main: MulqiGaming64\CaptchaVerification\CaptchaVerification

depend:
 - ImageOnMap